### ISSUE TITLE
Fork of GTAV-ENT?

### ISSUE THREAD

**Issue by gtav-ent** [thedroidgeek/GTAV-EnhancedFiveMTrainer#1]
Not that you have to, but wouldn't it have been easier to create a public fork of the project?

Also, I don't in principle mind adding things to suit FiveM as long as it doesn't make life easier for the lowest common denominator of script kiddies who want to mess up GTAO.

**Comment by thedroidgeek** [comment]
The thing is, I wasn't even planning to release the source code of my trainer until the FiveM moderators at reddit (where I posted it) were asking for it, so no actually, it wouldn't have been easier.
However, if you really want this to be seen as a fork of your project then I have no problem deleting this repo and forking yours before committing my changes, if this is what you mean (I'm still a git newbie, this is my first repo. I've even had to do some Googling before creating it).
Also, this trainer is just a temporary solution anyway, it's mainly made to compensate for the "missing core features" of FiveM (the player blips, player names on top of heads, ...), until server-side scripting gets implemented.
Btw, keep up the good work on ENT! The best GTA V trainer ever made.

**Comment by gtav-ent** [comment]
It's no problem for me, I only mention it because it looks like you're going to have a nightmare integrating further updates to ENT, whereas a fork gets them automatically merged (for the most part) for free.

**Comment by thedroidgeek** [comment]
Thank you very much but I don't really think I'll be needing to integrate any of the further updates to ENT, since I only took the code for the trainer menu and key configuration, which seem to work perfectly, and [removed everything else](http://i.imgur.com/hcqJysK.jpg).

**Comment by gtav-ent** [comment]
Fair enough, hadn't realised that's what you were doing. Well, good luck!

**Comment by thedroidgeek** [comment]
Thanks! :)
