### ISSUE TITLE
Question: any way to detect FiveM?

### ISSUE THREAD

**Issue by gtav-ent** [thedroidgeek/GTAV-EnhancedFiveMTrainer#3]
Hi again - question for you, as you may know by now: do you have any way to detect a FiveM session? 

Obviously you can check whether we're online using NETWORK::NETWORK_IS_GAME_IN_PROGRESS but I wondered if there's anything that tells us it's a FiveM game.

If not, no worries, just thought it worth asking.

**Comment by thedroidgeek** [comment]
I don't really know about that, I haven't dig in their source code yet ... But I don't think there should be anything really interesting about this there anyway.
If you're trying to prevent GTA: Online players from using your trainer then how about getting the parent process's path?
I'm not saying this is the best solution, but that's all I'm able to come out with right now ...
